apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: alabenhadjsalem/tododevops-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
