apiVersion: v1
kind: Service
metadata:
  name: kanban-backend-service
  namespace: kanban
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
      - name: http                          
        port: 5000                        
        targetPort: 5000
        nodePort: 30080 
  type: NodePort
